name: mindsave
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.9.1
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21